name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: v2ray
      run: |
        cd
        mkdir v2ray
        cd v2ray
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
        wget https://github.com/v2ray/v2ray-core/releases/download/v4.21.3/v2ray-linux-64.zip -O v2ray.zip
        unzip ngrok.zip
        unzip v2ray.zip
        rm -rf ngrok.zip v2ray.zip config.json
        ./ngrok authtoken 7GTsuP7sewoVemaBZrbZK_6C9w29ynA6r6TaSu6F2p5
        wget https://raw.githubusercontent.com/funnymdzz/v2actions/master/config.json 
        ./ngrok tcp 8080 &
    - name: hrhr
      run: |
       cd $HOME/v2ray
       ./v2ray
